@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseUrl = http://localhost:3000/api

@authToken = {{login.response.body.token}}

### Register user - Done
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "username": "NgocNguyen",
    "fullName": "NguyenThiNgoc",
    "password": "Cloud0208@",
    "email" : "ngoc.nguyen@hitachivantara.com"
}

### Login ThuongHuynh - Done
# @name login
POST {{baseUrl}}/auth/login 
Content-Type: {{contentType}}


{
    "usernameOrEmail": "ThuongThuong",
    "password": "Cloud0208@"
}


### Login NgocNguyen - Done
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "usernameOrEmail": "ngocnguyen",
    "password": "Cloud0208@"
}

### Change password - Done
PUT {{baseUrl}}/auth/password
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "newPassword": "Cloud0208@",
    "oldPassword": "Cloud0208@#"
}

### Update profile - Done
PUT {{baseUrl}}/user
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "fullName": "HuynhNgocThuong",
    "username": "ThuongThuong",
    "website": "thuonghuynh.com",
    "bio": "Hihi",
    "email": "huynhngocthuong0208@gmail.com"
}

### Follow user - Done
POST {{baseUrl}}/user/61c47dcf62bf2ec265797917/follow
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
}

### Change avatar user - User_1
PUT {{baseUrl}}/user/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{authToken}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="User_1.png"
Content-Type: image/png

< ./image/User_2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--