###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "NgocNguyen",
    "fullName": "NguyenThiNgoc",
    "password": "Cloud0208@",
    "email" : "ngoc.nguyen@hitachivantara.com"
}

### Login ThuongHuynh
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYxYmQ2MWU1ZWIxOGNmYjNhYmJhN2NmNiJ9.hNcfkvq824syfK6K9z8ppa5k04mheWmNgUsQpj6UFPQ

{
    "usernameOrEmail": "ThuongHuynh",
    "password": "Cloud0208@#"
}

### Login NgocNguyen
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYxYzQ3ZGNmNjJiZjJlYzI2NTc5NzkxNyJ9.ixRuGkrLUHU0bCu1s99e2Hdvn62NusYzkFcawAb-xZ4

{
    "usernameOrEmail": "ngocnguyen",
    "password": "Cloud0208@"
}

### Change password
PUT http://localhost:3000/api/auth/password
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYxYmQ2MWU1ZWIxOGNmYjNhYmJhN2NmNiJ9.hNcfkvq824syfK6K9z8ppa5k04mheWmNgUsQpj6UFPQ

{
    "newPassword": "Cloud0208@#",
    "oldPassword": "Cloud0208@"
}